[package]
name = "coin_selection"
version = "0.1.0"
authors = ["CoBloX Team <team@coblox.tech>"]
edition = "2018"

[dependencies]
bdk = { version = "0.4", default-features = false }
elements = "0.18"
estimate_transaction_size = { path = "../estimate_transaction_size" }
thiserror = "1"
