name: CI

on:
  pull_request:
  push:
    branches:
      - 'staging'
      - 'trying'
      - 'master'

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1.3.0

      - name: Check formatting
        uses: dprint/check@v1.5

      - name: Run clippy with default features
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Run clippy with all features
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  ui_e2e_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./e2e_tests
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1.3.0

      - name: Install Nigiri
        run: |
          mkdir ~/.nigiri; cd ~/.nigiri
          curl https://travis.nigiri.network | bash; cd
          docker-compose -f ~/.nigiri/docker-compose.yml up -d

      - name: Set up environment and build binaries
        run: |
          ./e2e_test_setup.sh

      - name: Run test
        run: |
          yarn install
          yarn run test

      - name: Archive logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Logfiles
          path: |
            ./e2e_tests/bobtimus.log
            ./e2e_tests/liquid.log
            ./e2e_tests/electrs.log
            ./e2e_tests/esplora.log

  build_test_workspace:
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu, x86_64-apple-darwin ]
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1.3.0

      - name: Cargo test (all workspace)
        if: matrix.os == 'ubuntu-latest'
        run: cargo test --workspace --all-features

      - name: Cargo build
        if: matrix.os == 'macos-latest'
        run: cargo build --workspace --all-features

  webapp_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache node_modules directory
        uses: actions/cache@v2
        with:
          path: |
            waves/node_modules
          key: node-modules-directory-${{ hashFiles('waves/yarn.lock') }}-v2

      - name: React tests
        run: |
          cd waves
          yarn install
          yarn run build
          yarn run test


  wasm_wallet_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1.3.0

      - name: Cache cargo and wasm-pack directories
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin
            ~/.cache/.wasm-pack
          key: ubuntu-rust-${{ steps.toolchain.outputs.rustc_hash }}-wasm-wallet-cargo-and-target-directory-${{ hashFiles('Cargo.lock') }}-v1

      - name: Install wasm-pack
        run: which wasm-pack || curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Extension wallet tests
        run: |
          cd extension/wallet
          wasm-pack test --firefox --headless

      - name: Upload artifact on test failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: wasm-wallet-test-binary
          path: ./target/wasm32-unknown-unknown/debug/deps/wallet-*.wasm
